In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
f = pd.read_csv('Credit_Risk_Data.csv')
f

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [3]:
# Filling null values

f.Gender=f.Gender.fillna("Female")
f.Married=f.Married.fillna("Yes")
f.Dependents=f.Dependents.fillna("3+")
f.Self_Employed=f.Self_Employed.fillna("Yes")
f.LoanAmount=f.LoanAmount.fillna(f.LoanAmount.mean())
f.Loan_Amount_Term=f.Loan_Amount_Term.fillna(12.0)
f.Credit_History=f.Credit_History.fillna(0.0)

In [4]:
#replacing the categorycal data to numerical 
#feature conversion 
f.Gender.replace({"Male":0, "Female":1},inplace=True)
f.Married.replace({"Yes":1, "No":0},inplace=True)
f.Dependents.replace({"0":0,"1":1,"2":2,"3+": 3},inplace=True)
f.Education.replace({"Graduate":1,"Not Graduate":0},inplace=True)
f.Self_Employed.replace({"Yes":1,"No":0},inplace=True)
f.Property_Area.replace({"Semiurban":1,"Urban":0,"Rural":2},inplace=True)
f.Loan_Status.replace({"Y":1,"N":0},inplace=True)


In [5]:
c=f.corr()
c

C:\Users\Chaitrali\AppData\Local\Temp\ipykernel_28380\1412802703.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  c=f.corr()


Gender   Married  Dependents  Education  Self_Employed  \
Gender             1.000000 -0.336818   -0.141975   0.061497       0.039440   
Married           -0.336818  1.000000    0.329805  -0.012304      -0.021584   
Dependents        -0.141975  0.329805    1.000000  -0.061179       0.030808   
Education          0.061497 -0.012304   -0.061179   1.000000       0.019059   
Self_Employed      0.039440 -0.021584    0.030808   0.019059       1.000000   
ApplicantIncome   -0.013933  0.051708    0.110073   0.140760       0.121356   
CoapplicantIncome -0.082316  0.075948    0.016073   0.062290       0.028834   
LoanAmount        -0.064609  0.147141    0.142395   0.166998       0.112118   
Loan_Amount_Term   0.053248 -0.078080   -0.037612   0.108617      -0.038786   
Credit_History    -0.035780 -0.018150   -0.034355   0.081637      -0.001923   
Property_Area     -0.017054 -0.004257   -0.025773  -0.065243       0.022732   
Loan_Status       -0.025407  0.091478   -0.003391   0.085884       0.005857   

                   ApplicantIncome  CoapplicantIncome  LoanAmount  \
Gender                   -0.013933          -0.082316   -0.064609   
Married                   0.051708           0.075948    0.147141   
Dependents                0.110073           0.016073    0.142395   
Education                 0.140760           0.062290    0.166998   
Self_Employed             0.121356           0.028834    0.112118   
ApplicantIncome           1.000000          -0.116605    0.565620   
CoapplicantIncome        -0.116605           1.000000    0.187828   
LoanAmount                0.565620           0.187828    1.000000   
Loan_Amount_Term         -0.016562          -0.050878    0.064207   
Credit_History            0.006986          -0.058795   -0.034518   
Property_Area             0.009500          -0.010522    0.044776   
Loan_Status              -0.004710          -0.059187   -0.036416   

                   Loan_Amount_Term  Credit_History  Property_Area  \
Gender                     0.053248       -0.035780      -0.017054   
Married                   -0.078080       -0.018150      -0.004257   
Dependents                -0.037612       -0.034355      -0.025773   
Education                  0.108617        0.081637      -0.065243   
Self_Employed             -0.038786       -0.001923       0.022732   
ApplicantIncome           -0.016562        0.006986       0.009500   
CoapplicantIncome         -0.050878       -0.058795      -0.010522   
LoanAmount                 0.064207       -0.034518       0.044776   
Loan_Amount_Term           1.000000        0.049195       0.082497   
Credit_History             0.049195        1.000000       0.018761   
Property_Area              0.082497        0.018761       1.000000   
Loan_Status                0.006561        0.432616      -0.032112   

                   Loan_Status  
Gender               -0.025407  
Married               0.091478  
Dependents           -0.003391  
Education             0.085884  
Self_Employed         0.005857  
ApplicantIncome      -0.004710  
CoapplicantIncome    -0.059187  
LoanAmount           -0.036416  
Loan_Amount_Term      0.006561  
Credit_History        0.432616  
Property_Area        -0.032112  
Loan_Status           1.000000

In [7]:
#dividing the dataset
data_x=f.iloc[:,1:12]
data_y=f.iloc[:,12]

In [8]:
from sklearn.model_selection import train_test_split


In [9]:
data_x_train,data_x_test,data_y_train,data_y_test=train_test_split(data_x,data_y,test_size=0.2,random_state=101)

In [10]:
data_x_train.shape,data_x_test.shape,data_y_train.shape,data_y_test.shape

((491, 11), (123, 11), (491,), (123,))

# Naive Bayes

In [11]:
from sklearn.naive_bayes import MultinomialNB

In [12]:
nb = MultinomialNB()

In [13]:
nb.fit(data_x_train,data_y_train)

MultinomialNB()

In [15]:
op = nb.predict(data_x_test)
op

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(data_y_test,op)

0.4796747967479675

# SVM

In [18]:
from sklearn.svm import SVC

In [19]:
s = SVC()

In [20]:
s.fit(data_x_train,data_y_train)

SVC()

In [21]:
op1 = s.predict(data_x_test)
op1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [22]:
accuracy_score(data_y_test,op1)

0.6341463414634146

#  KNN

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2)

In [28]:
knn.fit(data_x_train,data_y_train)

KNeighborsClassifier(n_neighbors=2)

In [29]:
op2 = knn.predict(data_x_test)
op2

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [30]:
accuracy_score(data_y_test,op2)

0.4959349593495935